# Generated by Django 4.1.1 on 2022-10-03 09:06

import chronos.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_profile_created_at_profile_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='image',
            field=models.ImageField(upload_to='watch', validators=[chronos.web.validators.file_size]),
        ),
    ]
