# Generated by Django 4.1.1 on 2022-10-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_alter_watchcomment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='price_paid',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
